export const coursesPG = [
  {
    name: "MBA",
    img: "courses2.jpg",
    description:
      "Master of Business Administration (MBA), is the best and highly-valued professional MBA degree Programme designed to develop the skills required for successful careers in business and management. With D.Y. Patil Vidyapeeth’s online learning or correspondence MBA program, the candidates will gain the right skills, knowledge, and attitude required to become successful in the global business environment. The MBA Programmes offered by DPU COL are approved by UGC and delivered via online mode where learners will gain their post-graduation management degree without the complexities of a full-time MBA Programme. Empower yourself by giving your career the right boost with DPU-COL’s online MBA program. This MBA degree program will help learners to gain insights on all the important concepts and practices as well as trends in their chosen area.",
    duration: "2 Years",
    mode: "Online / Hybrid",
    support: "Mentorship + Placement Guidance",
    specializations: [
      "Marketing Management",
      "Financial Management",
      "Human Resource Management",
      "International Business",
      "Operations Management",
      "Information Technology",
    ],
    universities: ["Jain University", "DY Patil University", "LPU"],
    colleges: ["IIM Ahmedabad", "IIM Bangalore", "XLRI"],
    accreditation: ["NAAC A++", "UGC Approved"],
  },
  {
    name: "MCA",
    img: "courses3.jpg",
    description:
      "The Master of Computer Applications (MCA) is a premier postgraduate degree that equips students with an advanced understanding of computer science and its real-world applications. This program is meticulously designed to provide a robust foundation in programming, algorithms, and software development, while also delving into specialized areas like data science, cloud computing, and cybersecurity. Students benefit from a curriculum that balances theoretical knowledge with extensive hands-on practice, preparing them for high-demand roles in the tech industry. With a focus on innovation and problem-solving, the MCA program empowers graduates to design and implement complex software solutions, manage IT projects, and drive technological advancement in a global context.",
    duration: "2 Years",
    mode: "Online",
    support: "24/7 Technical Support",
    specializations: [
      "System Management",
      "System Development",
      "System Engineering",
      "Management Information Systems (MIS)",
      "Networking",
      "Application Software Development",
    ],
    universities: ["Chandigarh University", "Amity University", "Manipal University"],
    colleges: ["NIT Trichy", "NIT Warangal", "VIT Vellore"],
    accreditation: ["NAAC A+", "AICTE Approved"],
  },
  {
    name: "M.Com",
    img: "courses4.jpg",
    description:
      "The Master of Commerce (M.Com) is a specialized postgraduate degree designed for individuals seeking to build expertise in the fields of commerce, finance, and accounting. This program offers an in-depth exploration of financial principles, economic theory, and business practices, preparing graduates for leadership roles in the corporate and financial sectors. The curriculum is structured to enhance analytical and decision-making skills, covering subjects such as corporate finance, international business, and advanced accounting. An M.Com degree opens doors to diverse career opportunities, including financial analysis, corporate accounting, and management consulting, equipping students with the knowledge to navigate the complexities of the modern economy.",
    duration: "2 Years",
    mode: "Distance Learning",
    support: "Dedicated Student Advisor",
    specializations: [
      "Finance",
      "Accounting",
      "Taxation",
      "Banking and Insurance",
      "International Business",
    ],
    universities: ["IGNOU", "Annamalai University", "University of Mumbai"],
    colleges: ["Shri Ram College of Commerce", "Loyola College", "St. Xavier's College"],
    accreditation: ["NAAC A", "UGC Recognized"],
  },
  {
    name: "MA",
    img: "courses5.jpg",
    description:
      "The Master of Arts (MA) is a versatile postgraduate degree that offers a deep dive into the humanities, social sciences, and fine arts. This program is designed for students who are passionate about critical thinking, cultural exploration, and in-depth research. Covering a wide array of disciplines such as literature, history, sociology, and philosophy, the MA encourages students to analyze complex societal issues and human experiences. Graduates are equipped with advanced research, communication, and analytical skills, making them well-suited for careers in academia, journalism, public policy, and the creative industries. The MA program provides a rich intellectual environment for students to pursue their academic interests and contribute to cultural and social discourse.",
    duration: "2 Years",
    mode: "Full-time / Part-time",
    support: "Career Counseling",
    specializations: [
      "English",
      "History",
      "Political Science",
      "Sociology",
      "Psychology",
      "Economics",
    ],
    universities: ["Delhi University", "Jawaharlal Nehru University", "University of Hyderabad"],
    colleges: ["Lady Shri Ram College for Women", "Miranda House", "Hindu College"],
    accreditation: ["NAAC A++", "UGC Approved"],
  },
];
