export const coursesUG = [
  {
    name: "BBA",
    img: "courses1.jpg",
    description:
      "The Bachelor of Business Administration (BBA) is an undergraduate degree that provides a strong foundation in business principles and management practices. This program is designed to equip students with the essential skills needed to thrive in the corporate world, covering key areas such as marketing, finance, human resources, and operations. The curriculum emphasizes practical learning through case studies, internships, and real-world projects, fostering leadership and entrepreneurial abilities. A BBA degree prepares graduates for a wide range of entry-level management positions and serves as an excellent stepping stone for further studies, such as an MBA.",
    duration: "3 Years",
    mode: "Online / Full-time",
    support: "Placement Assistance",
    specializations: [
      "Marketing",
      "Finance",
      "Human Resources",
      "International Business",
      "Entrepreneurship",
    ],
    universities: ["Narsee Monjee Institute of Management Studies", "Christ University", "Symbiosis International"],
    colleges: ["Shaheed Sukhdev College of Business Studies", "Anil Surendra Modi School of Commerce", "Madras Christian College"],
    accreditation: ["NAAC A+", "UGC Approved"],
  },
  {
    name: "BCA",
    img: "courses2.jpg",
    description:
      "The Bachelor of Computer Applications (BCA) is an undergraduate degree program focused on the fundamentals of computer science and its applications. It is designed for students who wish to pursue a career in the IT industry, providing a solid grounding in programming languages, database management, networking, and software development. The course structure combines theoretical learning with practical lab sessions, ensuring that students gain hands-on experience with the latest technologies. A BCA degree opens up various career paths in software development, system analysis, and IT support, and also provides a strong base for higher studies in computer science.",
    duration: "3 Years",
    mode: "Online / Full-time",
    support: "Internship Opportunities",
    specializations: [
      "Programming Languages (C++, Java, Python)",
      "Database Management Systems",
      "Web Development",
      "Networking",
      "Software Engineering",
    ],
    universities: ["Christ University", "Symbiosis Institute of Computer Studies and Research", "Loyola College"],
    colleges: ["St. Joseph's College", "Madras Christian College", "Stella Maris College"],
    accreditation: ["NAAC A", "AICTE Approved"],
  },
  {
    name: "B.Com",
    img: "courses3.jpg",
    description:
      "The Bachelor of Commerce (B.Com) is a comprehensive undergraduate degree that provides a strong foundation in commerce, finance, and accounting. This program is tailored for students aiming for careers in the financial and business sectors, offering in-depth knowledge of accounting principles, economic theory, and business law. The curriculum is designed to develop analytical and problem-solving skills, preparing students for roles in auditing, taxation, and financial management. A B.Com degree is a gateway to professional qualifications like Chartered Accountancy (CA) and also serves as a solid base for postgraduate studies in commerce and management.",
    duration: "3 Years",
    mode: "Online / Distance Learning",
    support: "Exam Preparation Support",
    specializations: [
      "Accounting and Finance",
      "Taxation",
      "Banking and Insurance",
      "Corporate Secretaryship",
      "E-Commerce",
    ],
    universities: ["University of Delhi", "University of Mumbai", "University of Calcutta"],
    colleges: ["Shri Ram College of Commerce", "Hindu College", "Lady Shri Ram College for Women"],
    accreditation: ["NAAC A++", "UGC Recognized"],
  },
  {
    name: "BA",
    img: "courses4.jpg",
    description:
      "The Bachelor of Arts (BA) is a versatile undergraduate degree that offers a broad education in the humanities, social sciences, and liberal arts. This program is ideal for students with a curiosity for understanding human culture, society, and creative expression. The BA curriculum encourages critical thinking, effective communication, and analytical skills through the study of subjects like literature, history, political science, and psychology. Graduates of the BA program are well-prepared for a diverse range of careers in fields such as education, media, public service, and the arts, and it provides a strong foundation for further academic pursuits.",
    duration: "3 Years",
    mode: "Full-time / Part-time",
    support: "Flexible Learning Schedule",
    specializations: [
      "English Literature",
      "History",
      "Political Science",
      "Sociology",
      "Psychology",
      "Economics",
    ],
    universities: ["St. Stephen's College", "Miranda House", "Loyola College"],
    colleges: ["Fergusson College", "St. Xavier's College", "Presidency College"],
    accreditation: ["NAAC A+", "UGC Approved"],
  },
];
